[toolchain]
channel = "1.91"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "arm-unknown-linux-gnueabihf",
  "aarch64-apple-darwin",
]
components = ["rustfmt", "clippy"]
